import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { motion } from 'framer-motion'
import Link from 'next/link'
import Image from 'next/image'

import { gql } from '@apollo/client'
import client from '../scripts/apollo-client'

export default function Home({ videos }) {
  // console.log('on the client ', videos)
  return (
    <div className="container mx-auto">
      <Head>
        <title>Split the Facts: Parodies and comic sketches. Enjoy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.ul layoutId="nav">
        <li>
          <Link href="/">
            <a>Home</a>
          </Link>
        </li>
      </motion.ul>
      <motion.h1
        className="font-PlayfairDisplay text-3xl font-semibold text-center"
        layoutId="title"
      >
        Split! - The West at War with Itself
      </motion.h1>

      <main className={styles.main}>
        {videos &&
          videos.map((video) => {
            return (
              <div key={video.id} className="m-10 border- border-yellow-200">
                <p className="text-xl">{video.title}</p>
                <Image
                  src={video.thumbnail_image.url}
                  width={192}
                  height={108}
                />
                <p>{video.description}</p>
              </div>
            )
          })}
      </main>

      {/* <footer className={styles.footer}></footer> */}
    </div>
  )
}

export async function getStaticProps() {
  console.log('im on the server')
  const { data } = await client.query({
    query: gql`
      query {
        videos {
          title
          id
          description
          thumbnail_image {
            url
          }
          hero_image {
            url
          }
        }
      }
    `
  })

  // console.log(' ===== data ', data)

  return {
    props: {
      videos: data.videos
    }
  }
}
