import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { EmailForm } from '../components/Form'
import { motion } from 'framer-motion'
import Link from 'next/link'

export default function Home() {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Split the Facts: Parodies and comic sketches. Enjoy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.ul layoutId="nav">
        <li>
          <Link href="/">
            <a>Home</a>
          </Link>
        </li>
      </motion.ul>
      <motion.h1
        className="font-PlayfairDisplay text-3xl font-semibold text-center"
        layoutId="title"
      >
        Split! - The West at War with Itself
      </motion.h1>

      <main className={styles.main}>
        <motion.img
          layoutId="img"
          className={styles.rounded}
          src="https://yt3.ggpht.com/ytc/AAUvwnh1BcLZ9z1FADbBWugEfNT6_6jLl8M1Pi3RJzca=s176-c-k-c0x00ffffff-no-rj"
        />
        <motion.p className={styles.description} layoutId="subtitle">
          Channel for parodies and comedic sketches. Enjoy!
        </motion.p>

        <div>
          <p className={styles.title}>
            Patreon{' '}
            <a href="https://www.patreon.com/user/posts?u=56069659">
              @Sam Roffey
            </a>
          </p>
          <p className={styles.title}>
            YouTube{' '}
            <a href="https://www.youtube.com/channel/UCjRNMsglFYFwNsnOWIOgt1Q">
              @Split! - The West at War with Itself
            </a>
          </p>
          <p className={styles.title}>
            Email{' '}
            <a href="mailto:split.thefacts@gmail.com">
              split.thefacts@gmail.com
            </a>
          </p>
          <p className={styles.title}>
            Instagram
            <a href="https://www.instagram.com/split_the_facts">
              @split_the_facts
            </a>
          </p>
          <p className={styles.title}>
            TikTok
            <a href="https://www.tiktok.com/@split_the_facts?lang=en">
              @split_the_facts
            </a>
          </p>
          <p className={styles.title}>
            Reddit{' '}
            <a href="https://www.reddit.com/user/SplitTheFacts">
              @SplitTheFacts
            </a>
          </p>
        </div>

        <div>
          <EmailForm />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
