import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import EmailForm from '../components/Form'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Split the Facts: Parodies and comic sketches. Enjoy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.notoSerif}>
          Split! - The West at War with Itself
        </h1>
        <img
          className={styles.rounded}
          src="https://yt3.ggpht.com/ytc/AAUvwnh1BcLZ9z1FADbBWugEfNT6_6jLl8M1Pi3RJzca=s176-c-k-c0x00ffffff-no-rj"
        />
        <p className={styles.description}>
          Channel for parodies and comedic sketches. Enjoy!
        </p>

        <EmailForm />

        <div>
          <p className={styles.title}>
            Patreon{' '}
            <a href="https://www.patreon.com/user/posts?u=56069659">
              @Sam Roffey
            </a>
          </p>
          <p className={styles.title}>
            YouTube{' '}
            <a href="https://www.youtube.com/channel/UCjRNMsglFYFwNsnOWIOgt1Q">
              @Split! - The West at War with Itself
            </a>
          </p>
          <p className={styles.title}>
            Email{' '}
            <a href="mailto:split.thefacts@gmail.com">
              split.thefacts@gmail.com
            </a>
          </p>
          <p className={styles.title}>
            Instagram
            <a href="https://www.instagram.com/split_the_facts">
              @split_the_facts
            </a>
          </p>
          <p className={styles.title}>
            TikTok
            <a href="https://www.tiktok.com/@split_the_facts?lang=en">
              @split_the_facts
            </a>
          </p>
          <p className={styles.title}>
            Reddit{' '}
            <a href="https://www.reddit.com/user/SplitTheFacts">
              @SplitTheFacts
            </a>
          </p>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
