import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { HookForm } from '../components/HookForm'
import { motion } from 'framer-motion'
import Link from 'next/link'
import { FaYoutube, FaPatreon } from 'react-icons/fa'

export default function Home() {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Split the Facts: Parodies and comic sketches. Enjoy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <motion.ul layoutId="nav">
        <li>
          <Link href="/alt">
            <a>ALT</a>
          </Link>
        </li>
      </motion.ul> */}
      <motion.h1
        className="font-PlayfairDisplay text-3xl font-semibold text-center m-10"
        layoutId="title"
      >
        Split! - The West at War with Itself
      </motion.h1>
      <main className={styles.main}>
        <motion.img
          className="rounded-full mx-auto my-10"
          width="90px"
          height="90px"
          layoutId="img"
          src="https://yt3.ggpht.com/ytc/AAUvwnh1BcLZ9z1FADbBWugEfNT6_6jLl8M1Pi3RJzca=s176-c-k-c0x00ffffff-no-rj"
        />
        <motion.p
          className="w-80 md:w-1/2 lg:w-1/2 my-4 mx-auto text-center text-xl font-NotoSerif"
          layoutId="subtitle"
        >
          Channel for parodies and comedic sketches. Enjoy!
        </motion.p>
        <div className="w-90 px-5 md:w-66 lg:w-1/2 mx-auto">
          <div className="flex flex-col md:flex-row w-full border- border-red-300">
            <a
              href="https://www.youtube.com/channel/UCjRNMsglFYFwNsnOWIOgt1Q"
              className="flex flex-row md:flex-col lg:flex-row shadow-sm p-4 hover:shadow-lg md:w-1/2 w-100 border-0 border-green-50"
            >
              <FaYoutube className="text-4xl mr-4 text-red-500" />
              <div className="flex flex-col">
                <p className="text-xl">
                  My YouTube Channel &rarr; <br />
                </p>
                <p className="text-green-600 text-md">
                  @Split! - The West at War with Itself
                </p>
              </div>
            </a>

            <a
              href="https://www.patreon.com/user/posts?u=56069659"
              className="flex flex-row md:flex-col lg:flex-row shadow-sm p-4 md:w-1/2 hover:shadow-lg w-100 border-0 border-green-50"
            >
              <FaPatreon className="text-2xl mr-4 text-red-500" />
              <div className="flex flex-col">
                <p className="text-xl">Support my Patreon &rarr; </p>
                <p className="text-green-600">@Sam Roffey</p>
              </div>
            </a>
          </div>
        </div>
        <div className="w-100 px-2 md:w-4/5 lg:w-1/2 mx-auto my-10 border-2 border-red-400">
          <HookForm />
        </div>
        <div className="w-full px-2 md:w-5/6 lg:w-1/3 mx-auto border- md:border-red-400 text-left lg:text-center">
          <p className={styles.title}>
            Email&nbsp;{' '}
            <a
              href="mailto:split.thefacts@gmail.com"
              className="text-green-600"
            >
              split.thefacts@gmail.com
            </a>
          </p>
          <p className={styles.title}>
            Instagram &nbsp;
            <a
              href="https://www.instagram.com/split_the_facts"
              className="text-green-600"
            >
              @split_the_facts
            </a>
          </p>
          <p className={styles.title}>
            TikTok &nbsp;
            <a
              href="https://www.tiktok.com/@split_the_facts?lang=en"
              className="text-green-600"
            >
              @split_the_facts
            </a>
          </p>
          <p className={styles.title}>
            Reddit &nbsp;{' '}
            <a
              href="https://www.reddit.com/user/SplitTheFacts"
              className="text-green-600"
            >
              @SplitTheFacts
            </a>
          </p>
        </div>
      </main>

      <footer className="mb-20"></footer>
    </div>
  )
}
