import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Split the Facts: Parodies and comic sketches. Enjoy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.notoSerif}>
          Split! - The West at War with Itself
        </h1>
        <img
          className={styles.rounded}
          src="https://yt3.ggpht.com/ytc/AAUvwnh1BcLZ9z1FADbBWugEfNT6_6jLl8M1Pi3RJzca=s176-c-k-c0x00ffffff-no-rj"
        />
        <p className={styles.description}>
          Channel for parodies and comedic sketches. Enjoy!
        </p>

        <div className={styles.grid}>
          <a
            href="https://www.patreon.com/user/posts?u=56069659"
            className={styles.card}
          >
            <h3>Patreon &rarr;</h3>
            <p>Support my content</p>
          </a>

          <a
            href="https://www.youtube.com/channel/UCjRNMsglFYFwNsnOWIOgt1Q"
            className={styles.card}
          >
            <h3>YouTube &rarr;</h3>
            <p>Watch all my videos</p>
          </a>
          <a href="mailto:split.thefacts@gmail.com" className={styles.card}>
            <h3>Email &rarr;</h3>
            <p>split.thefacts@gmail.com</p>
          </a>
          <a
            href="https://www.instagram.com/split_the_facts"
            className={styles.card}
          >
            <h3>Instagram &rarr;</h3>
            {/* <p>@split_the_facts</p> */}
            {/* <p>
              TikTok
              [@split_the_facts](https://www.tiktok.com/@split_the_facts?lang=en)
            </p>
            <p>
              Reddit [@SplitTheFacts](https://www.reddit.com/user/SplitTheFacts)
            </p> */}
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
