import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { motion } from 'framer-motion'
import { gql } from '@apollo/client'
import client from '../scripts/apollo-client'
import Link from 'next/link'

import { YearbookImage } from '../components/YearbookImage'

export default function Yearbook({ characters }) {
  console.log('on the client characters = ', characters)
  return (
    <div className="container mx-auto">
      <Head>
        <title>Split the Facts: Parodies and comic sketches. Enjoy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.ul layoutId="nav">
        <li>
          <Link href="/">
            <a>Home</a>
          </Link>
        </li>
      </motion.ul>

      <main className={styles.main}>
        <div className="flex flex-row w-full">
          {characters &&
            characters.map((character) => {
              return (
                <div key={character.id} className="m-10 ">
                  <YearbookImage character={character} key={character.id} />
                </div>
              )
            })}
        </div>
      </main>
      {/* <footer className={styles.footer}></footer> */}
    </div>
  )
}

export async function getStaticProps() {
  console.log('im on the server')
  const { data } = await client.query({
    query: gql`
      query {
        characters {
          id
          name
          image {
            url
          }
          image_hover {
            url
          }
        }
      }
    `
  })

  // console.log(' ===== data ', data)

  return {
    props: {
      characters: data.characters
    }
  }
}
